#!/bin/bash
#
# Perform necessary ruby193 setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mv /opt/omnibus/ruby193/scl /etc/scl/prefixes/omnibus-ruby193

echo "Thank you for installing ruby193!"

exit 0
